### ISSUE TITLE
Erro 500 (Internal Server Error)

### ISSUE THREAD

**Issue by rodriguesabner** [JonathanLemes/PagSeguro-Payment#1]
Fala cara, td bem? Tentei usar sua API mas quando tento fazer um checkout transparente me retorna o erro 500. 

Copiei do pagseguro e da o mesmo erro, sabe o pq?

Link
https://documenter.getpostman.com/view/4711102/SVfGyC4D?version=latest#efdf0a7b-cec4-4275-9a26-3f98acf4fbd9

**Comment by JonathanLemes** [comment]
Chegou a ver se não está confundindo o token do sandbox (ambiente de testes) com o do ambiente real?

**Comment by rodriguesabner** [comment]
Então, troquei todos os links pra o Sandbox, mas o erro continua... Nem o log fala nada

**Comment by JonathanLemes** [comment]
O checkout transparente exige que você crie uma sessão (para isso, existe a função createSession() na própria lib) e, caso você use algum cartão, é necessário também importar uma biblioteca JS do próprio PagSeguro para gerar o token do cartão (confome em https://dev.pagseguro.uol.com.br/reference/checkout-transparente#transparente-gerando-uma-sessao).

Você está seguindo esses passos no seu código antes de realizar o checkout?

**Comment by rodriguesabner** [comment]
Estava fazendo tudo certinho e tava dando esse erro, inclusive a parte do token e hash.

Perdi a paciencia,criei uma nova conta e funcionou kkkkkk, com os mesmos dados.
Deve ser erro interno deles, valeu pela atenção Jonathan!

**Comment by JonathanLemes** [comment]
Tranquilo irmão, qualquer outro problema estou por aqui 😉
